export const PROFILES = 
[
    {
        "id": 0,
        "gender": "male",
        "firstName": "Gadi",
        "lastName": "Gross",
        "pw": "123",
        "userName": "gads",
        "email": "gadi@gmail.com",
        "birthDate": "new Date",
        "photos": ["../images/male.jpg","../images/male2.jpg", "../images/male3.jpg"],
        "scratches": [
            "0",
            "3",
            "2",
            "5",
            "4",
            "11",
            "10",
            "20",
            "23",
            "21",
            "6"
                ]
        },
        
        {
        "id": 1,
        "gender": "male",    
        "firstName": "Nadav",
        "lastName": "Almagor",
        "pw": "123",
        "userName": "nadi",
        "email": "nadav@gmail.com",
        "birthDate":" new Date",
        "photos": ["../images/male4.jpg", "../images/male5.jpg" , "../images/male6.jpg"],
        "scratches": [
            "1",
            "3",
            "4",
            "5",
            "0",
            "20",
            "21",
            "22",
            "23"
            ]
        },
        {
            "id": 2,
            "gender": "female",
            "firstName": "lior",
            "lastName": "sela",
            "pw": "123",
            "userName": "lili",
            "email": "lior@gmail.com",
            "birthDate": "new Date",
            "photos": ["../images/female.jpg", "../images/female1.jpg", "../images/female2.jpg"],
            "scratches": [
                "12",
                "22",
                "13",
                "15",
                "19",
                "5",
                "8",
                "3",
                "0",
                "21",
                "4",
                "6"
                ]
            },
            {
            "id": 3,
            "gender": "female",
            "firstName": "מיטל",
            "lastName": "כהן",
            "pw": "123",
            "userName": "meitalush",
            "email": "meital@gmail.com",
            "birthDate": "new Date",
            "photos": ["../images/female3.jpg", "../images/female4.jpg", "../images/female5.jpg"],
            "scratches": [
                "0",
                "4",
                "5",
                "1",
                "3",
                "2",
                "13",
                "14",
                "15",
                "16",
                "23"
                ]
            },
            {
                "id": 4,
                "gender": "male",
                "firstName": "רון",
                "lastName": "שדה",
                "pw": "123",
                "userName": "רונצו",
                "email": "ron@gmail.com",
                "birthDate": "new Date",
                "photos": ["../images/male8.jpg", "../images/male6.jpg", "../images/male7.jpg"],
                "scratches": [
                    "23",
                    "22",
                    "21",
                    "20",
                    "1",
                    "10",
                    "13",
                    "12",
                    "15",
                    "14",
                    "6"
                        ]
                },
                
                {
                "id": 5,
                "gender": "male",    
                "firstName": "שי",
                "lastName": "אלמגור",
                "pw": "123",
                "userName": "שייצוק",
                "email": "shai@gmail.com",
                "birthDate": "new Date",
                "photos": ["../images/male9.jpg", "../images/male10.jpg", "../images/male8.jpg"],
                "scratches": [
                    "1",
                    "3",
                    "4",
                    "5",
                    "9",
                    "7",
                    "8",
                    "13",
                    "12",
                    "15",
                    "14"
                    ]
                },
                
                {
                "id": 6,
                "gender": "female",
                "firstName": "Dana",
                "lastName": "galon",
                "pw": "123",
                "userName": "danush",
                "email": "dana@gmail.com",
                "birthDate": "new Date",
                "photos": ["../images/female.jpg", "../images/female1.jpg", "../images/female2.jpg"],
                "scratches": [
                    "0",
                    "4",
                    "9",
                    "1",
                    "3",
                    "2",
                    "7",
                    "8",
                    "12",
                    "22",
                    "15",
                    "17",
                    "20"
                    ]
                },
                {
                "id": 7,
                "gender": "female",
                "firstName": "תרצה",
                "lastName": "גלאון",
                "pw": "123",
                "userName": "tirta123",
                "email": "rirtza@gmail.com",
                "birthDate": "new Date",
                "photos": ["../images/female6.jpg", "../images/female4.jpg", "../images/female5.jpg"],
                "scratches": [
                    "9",
                    "4",
                    "5",
                    "1",
                    "7",
                    "8",
                    "3",
                    "11",
                    "19",
                    "18",
                    "13",
                    "15",
                    "14"
                    ]
                }
    ]
