export const SCRATCHES = [
    { "id": 0, "type": "הרגלים מגונים", "subType": "מחרפן אות", "header": "קמצנות", "desc": "זה אומר הכל על האישיות של הבן אדם", "author": "", "likes": 34, "dislikes": 23, "addedToProfile": 0},
    { "id": 1, "type": "גוף", "subType": "שונא/ת", "header": "אוי רגליים", "desc": "לא סובל שנוגעים לי ברגליים", "author": "", "likes": 45, "dislikes": 23, "addedToProfile": 0},
    { "id": 2, "type": "גוף", "subType": "חולה על זה ברמות", "header": "קיצי בגב", "desc": "אני הופך לכלבלב", "author": "", "likes": 14, "dislikes": 12, "addedToProfile": 0},
    { "id": 3, "type": "הרגלים מגונים", "subType": "מחרפן אות", "header": "אמאלה הריח", "desc": "רגישות קשה לריחות", "author": "", "likes": 25, "dislikes": 34, "addedToProfile": 0},
    { "id": 4, "type": "הרגלים מגונים", "subType": "שונא/ת", "header": "נחירות", "desc": "לא אפשרי לישון עם זה", "author": "", "likes": 12, "dislikes": 35, "addedToProfile": 0},
    { "id": 5, "type": "נפש", "subType": "שונא/ת", "header": "בוקר חפירות", "desc": "אין עם מי לדבר בבוקר", "author": "", "likes": 23, "dislikes": 56, "addedToProfile": 0},
    { "id": 6, "type": "הרגלים מגונים", "subType": "loveSubTyp", "header": "בעיות שינה", "desc": " לא מצליחה להירדם בלי טלויזיה...", "author": "", "likes": 34, "dislikes": 23, "addedToProfile": 0},
    { "id": 7, "type": "גוף", "subType": "שונא/ת", "header": "ריח פה", "desc": "זה מגעיל אותי ברמות", "author": "", "likes": 23, "dislikes": 54, "addedToProfile": 0},
    { "id": 8, "type": "הרגלים מגונים", "subType": "מחרפן אות", "header": "לאכול בפה פתוח", "desc": "מה אני צריך לראות את  התהליך הזה בפה שלך!!", "author": "", "likes": 78, "dislikes": 45, "addedToProfile": 0},
    { "id": 9, "type": "הרגלים מגונים", "subType": "freaksSubTyp", "header": "ציפרוניים", "desc": "ציפורניים ארוכות לגברים??? ", "author": "", "likes": 34, "dislikes": 56, "addedToProfile": 0},
    { "id": 10, "type": "גוף", "subType": "אוהב/ת", "header": "מסאג' רגליים", "desc": "מוריד ממני את כל לחצי היום!", "author":"", "likes": 23, "dislikes": 54, "addedToProfile": 0},
    { "id": 11, "type": "הרגלים מגונים", "subType": "מחרפן אות", "header": "גירוד רגליים", "desc": "מה אתם חופרים שם?? תנקו את זה!!", "author": "", "likes": 0, "dislikes": 34, "addedToProfile": 0},
    { "id": 12, "type": "הרגלים מגונים", "subType": "שונא/ת", "header": "להירדם עם...", "desc": "לא מצליחה להירדם עם משהו ברקע...", "author": "", "likes": 24, "dislikes": 45, "addedToProfile": 0},
    { "id": 13, "type": "נפש", "subType": "hateSubTyp", "header": "חפירות", "desc": "פשוט לא מצליח לשרוד את זה", "author": "", "likes": 46, "dislikes": 24, "addedToProfile": 0},
    { "id": 14, "type": "נפש", "subType": "חולה על זה ברמות", "header": "שיחות על הבוקר", "desc": "מוח לא עובד לפני 2 כוסות קפה", "author": "", "likes": 66, "dislike": 44, "addedToProfile": 0},
    { "id": 15, "type": "הרגלים מגונים", "subType": "מחרפן אות", "header": "ציפרוניים", "desc": "כסיסת ציפורניים...איכססס", "author": "", "likes": 34, "dislikes": 57, "addedToProfile": 0},
    { "id": 16, "type": "הרגלים מגונים", "subType": "חולה על זה ברמות", "header": "לאכול בפה פתוח", "desc": "מה אני צריך לראות את  התהליך הזה בפה שלך!!", "author": "", "likes": 34, "dislikes": 36, "addedToProfile": 0},
    { "id": 17, "type": "הרגלים מגונים", "subType": "מחרפן אות", "header": "ריח רגליים", "desc": "לא יכול לסבול את זה!!", "author": "", "likes": 26, "dislikes": 36, "addedToProfile": 0},
    { "id": 18, "type": "נפש", "subType": "שונא/ת", "header": "שיחות על הבוקר", "desc": "מוח לא עובד לפני 2 כוסות קפה", "author": "", "likes": 45, "dislikes": 67, "addedToProfile": 0},
    { "id": 19, "type": "הרגלים מגונים", "subType": "מחרפן אות", "header": "זקנים", "desc": "זה מגרד ונראה ממש מוזר", "author": "", "likes": 67, "dislikes": 35, "addedToProfile": 0},
    { "id": 20, "type": "גוף", "subType": "אוהב/ת", "header": "ליטוף בשיער", "desc": "אפשר לפתור הכל עם קצת ליטופי שיער", "author": "", "likes": 26, "dislikes": 34, "addedToProfile": 0},
    { "id": 21, "type": "נפש", "subType": "חולה על זה ברמות", "header": "נדנודים", "desc": "לא צריך להגיד לי כל כמה דקות מה נסגר", "author": "", "likes": 24, "dislikes": 87, "addedToProfile": 0},
    { "id": 22, "type": "גוף", "subType": "אוהב/ת", "header": "מסאג' רגליים", "desc": "מתמסרת כמו כלבלב קטן ומחזירה פינוק פי אלף", "author": "", "likes": 65, "dislikes": 45, "addedToProfile": 0},
    { "id": 23, "type": "נפש", "subType": "שונא/ת", "header": "צעקות", "desc": "לא מבין איך זה תורם לשום דבר ורק יוצר עוד כעס", "author": "", "likes": 54, "dislikes": 45, "addedToProfile": 0},
    { "id": 24, "type": "הרגלים מגונים", "subType": "שונא/ת", "header": "קמצנות", "desc": "זה מוריד לי ברמות", "author": "", "likes": 34, "dislikes": 25, "addedToProfile": 0},
    { "id": 25, "type": "גוף", "subType": "שונא/ת", "header": "ריח זיעה בגוף", "desc": "זה מגעיל אותי ומוריד לי כל חשק", "author": "", "likes": 56, "dislikes": 67, "addedToProfile": 0}
]