export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_SCRATCH = 'ADD_SCRATCH';
export const UPDATE_SCRATCH = 'ADD_SCRATCH';
export const INCREMENT_LIKES = 'INCREMENT_LIKES'